#!/usr/bin/python
# -*- coding: utf-8-unix; -*-
#
# Copyright © 2013-2014, Nicolas CANIART <nicolas@caniart.net>
#
# Author(s):
#   Nicolas CANIART <nicolas@caniart.net>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.
#
import sys

from vcs_ssh import parse_args, main


if '__main__' == __name__:
    args = parse_args(sys.argv[1:])
    sys.exit(main(**args))


# vim: syntax:tw=4:sw=4:et:

