#!/usr/bin/python
# -*- coding: utf-8; -*-
#
#  Copyright © 2013-2014, Nicolas CANIART <nicolas@caniart.net>
#
#  This file is part of vcs-ssh.
#
#  vcs-ssh is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  vcs-ssh is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with vcs-ssh.  If not, see <http://www.gnu.org/licenses/>.
#
import os
import sys
import logging

try:
    from xdg import BaseDirectory
    log_path = BaseDirectory.save_data_path('vcs-ssh')
    log_path = os.path.join(log_path, 'vcs-ssh.log')

except ImportError:
    if 'XDG_DATA_HOME' in os.environ:
        log_path = os.path.join(os.environ['XDG_DATA_HOME'],
                                'vcs-ssh')
        if not os.path.isdir(log_path):
            os.makedirs(log_path)
        log_path = os.path.join(log_path, 'vcs-ssh.log')

finally:
    if 'log_path' not in locals():
        log_path = os.environ['HOME']
        if not os.path.isdir(log_path):
            os.makedirs(log_path)
        log_path = os.path.join(log_path, 'vcs-ssh.log')

from vcs_ssh import parse_args, main


if '__main__' == __name__:
    if os.getenv('COVERAGE_PROCESS_START') is not None:
        try:
            import coverage
            coverage.process_startup()
        except ImportError:
            pass
    args = parse_args(sys.argv[1:])
    logger = logging.getLogger('vcs-ssh')
    logger.addHandler(logging.FileHandler(log_path))
    if 'VCS_SSH_DEBUG' in os.environ:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    sys.exit(main(**args))


# vim: syntax=python:sws=4:sw=4:et:
